# Configuration for Alacritty, the GPU enhanced terminal emulator.

# Setup term for programs to be able to use it
env:
  TERM: xterm-256color

window:
   padding:
    x: 45
    y: 45

   decorations: transparent

font:
  normal:
    family: Liga SFMono Nerd Font
    style: Light

  # Bold font face
  bold:
    family: Liga SFMono Nerd Font
    style: Bold

  # Italic font face
  italic:
    family: Liga SFMono Nerd Font
    style: Italic

  # Font size
  size: 14.0

mouse:
  hide_when_typing: true

color_schemes:
  nano_light: &nano_light
    primary:
      background: '0xFFFFFF'
      foreground: '0x37474F'

    cursor:
      cursor: '0x37474F'

    normal:
      black:   '0x000000'
      red:     '0xFF6961'
      green:   '0x028e2c'
      yellow:  '0xFFaB91'
      blue:    '0x0098dd'
      magenta: '0x673AB7'
      cyan:    '0x81A1C1'
      white:   '0xFAFAFA'

    bright:
      black:   '0x000000'
      red:     '0xFF6961'
      green:   '0x028e2c'
      yellow:  '0xFFaB91'
      blue:    '0x0098dd'
      magenta: '0x673AB7'
      cyan:    '0x81A1C1'
      white:   '0xFAFAFA'

    indexed_colors: []

  nano_dark: &nano_dark
    primary:
      background: '0x2E3440'
      foreground: '0xD8DEE9'
  
    # Normal colors
    normal:
      black:   '0x3B4252'
      red:     '0xBF616A'
      green:   '0xA3BE8C'
      yellow:  '0xEBCB8B'
      blue:    '0x81A1C1'
      magenta: '0xB48EAD'
      cyan:    '0x88C0D0'
      white:   '0xE5E9F0'
  
    # Bright colors
    bright:
      black:   '0x4C566A'
      red:     '0xBF616A'
      green:   '0xA3BE8C'
      yellow:  '0xEBCB8B'
      blue:    '0x81A1C1'
      magenta: '0xB48EAD'
      cyan:    '0x8FBCBB'
      white:   '0xECEFF4'
  
    indexed_colors: []

colors: *nano_light

cursor:
  # Cursor style
  style:
    shape: beam
